### ISSUE TITLE
Refactor the access to the files content

### ISSUE THREAD

**Issue by felipegustavo** [visminer/RepositoryMiner#119]
Has an overhead when files are accessed to get their content. The current way was proper until the release 0.8, because checkout was not used, so the file snapshot is accessed from git index. But now, the checkout is made and to access the files directly is much faster than using git index. Therefor, the refactoring of this process is needed to improve the performance.

**Comment by luispscarvalho** [comment]
You may associate this issue with the forthcoming release candidate 1.2.0.

**Comment by luispscarvalho** [comment]
Please, add/edit a milestone to properly wrap this issue.
