### ISSUE TITLE
Uso do singleton pattern para conexão com o banco de dados

### ISSUE THREAD

**Issue by joaoviss** [visminer/RepositoryMiner#82]
Me parece razoável que uma classe de conexão ao banco de dados (br.edu.ufba.softvis.visminer.config.DBConfig) tenha apenas uma instância em execução por vez. Isso reduziria o tráfego de dados na rede e o consumo de memória o que traria ganho em desempenho e escalabilidade.

**Comment by luispscarvalho** [comment]
Concordo com David
