### ISSUE TITLE
Arquivo de configuração do repositório

### ISSUE THREAD

**Issue by joaoviss** [visminer/RepositoryMiner#83]
Poderia haver um arquivo XML de onde seriam recuperadas a informações do repositório como nome, descrição, dono, endereço... Isso tornaria o código mais legível.

**Comment by luispscarvalho** [comment]
Não acho que deva existir um arquivo de configuração, XML ou PROPERTIES, no VISMINER "CORE". Ele é um componente para outros softwares. Estes outros é que decidem como são armazenadas as strings de configuração. Se, por exemplo, o software "A" utilliza arquivos PROPERTIES (para configurar-se e configurar outras ferramentas/componentes) e o VISMINER "CORE" pede por um XML, "A" vai ter que manter duas formas de registro de configurações, PROPERTIES e XML.
